### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by blacowboy** [okatu-loli/koishi-plugin-leetcode-daily-question#1]
![image](https://github.com/okatu-loli/koishi-plugin-leetcode-daily-question/assets/162235684/8ccf8799-9c56-4ead-a6c3-c5732e2ef8d7)

**Comment by okatu-loli** [comment]
我上传了一个新版本
删除插件, 重启koishi, 重新安装再试试

**Comment by blacowboy** [comment]
![image](https://github.com/okatu-loli/koishi-plugin-leetcode-daily-question/assets/162235684/a35d9d9f-ab68-4e19-8172-796b428d02c8)

还是不行

**Comment by okatu-loli** [comment]
了解，刚刚了解koishi有ctx.http封装了fetch,我的锅，我稍后更新

**Comment by okatu-loli** [comment]
更新了版本，再试试呢？

**Comment by blacowboy** [comment]
好了谢谢
